/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/home'
import { Route as OrganizationsOrganizationIdImport } from './routes/organizations/$organizationId'

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationsOrganizationIdRoute =
  OrganizationsOrganizationIdImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
}

export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/home': typeof HomeRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/organizations/$organizationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/organizations/$organizationId'
  id: '__root__' | '/home' | '/organizations/$organizationId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  OrganizationsOrganizationIdRoute: typeof OrganizationsOrganizationIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  OrganizationsOrganizationIdRoute: OrganizationsOrganizationIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/home",
        "/organizations/$organizationId"
      ]
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/organizations/$organizationId": {
      "filePath": "organizations/$organizationId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
